### ISSUE TITLE
[Question] Setting up AppBridge for Dev Mode

### ISSUE THREAD

**Issue by BRS999** [bullhorn/extension-samples#1]
I've read through the sample projects and I believe I've set things up correctly.

I've added the appBridgeFactory to a module as such.

```
let bridge: AppBridge;
export function appBridgeFactory(http: Http): AppBridge {
    if (!bridge) {
        if ( environment.production ) {
            bridge = new AppBridge('Test prod');
        } else {
            bridge = new DevAppBridge('Test dev', http);
        }
        bridge.register();
        bridge.tracing = true;
    }
    return bridge;
}
```
I've also included it under providers: 

```
      provide: AppBridge,
      useFactory:  appBridgeFactory,
      deps: [ Http ]
```
I've also `--disable-host-check` on start.

Now when I try to get an entity I get a 404.

`http://localhost:4200/undefined/entity/Lead/6109827 404 (Not Found)`

This is the method I use to get the entity.

```
this.bridge.httpGET('entity/Lead/6109827')
    .then( 
      x => console.log(x), 
      error => console.log('error', error));
```
Did I miss something with the setup? This may be unrelated but I don't see this cookie `UlEncodedIdentity` when I'm logged into BH.

This is in reference to [https://github.com/bullhorn/novo-elements/issues/551](url) so apologizes for the double post.

Thanks again!

**Comment by ndickerson** [comment]
So I know that this question is over 2 years old now, and the need in this particular situation has most likely already been solved. However, wanted to point out that the new extensions for 2019 are here, and instructions for running them and using App Bridge should be very straightforward and greatly simplified from what they were. The extensions should all run by following the steps in the README files, and will work the same whether users are Novo enabled or not. Cheers!
